### ISSUE TITLE
Windows DLL imports.

### ISSUE THREAD

**Issue by ragnarlodbrok1992** [MasterQ32/SDL.zig#102]
Hi,
While working with SDL2 in Zig I tried to build whole library trying to incoporate TTF inside my engine. I found out that build cannot find sdl2_image trying to import DLL:

`D:\engines\zig-longship-engine\libs\SDL.zig(master -> origin)
λ zig build
LLD Link... error(link): DLL import library for -lsdl2_image not found
error: DllImportLibraryNotFound
error: demo-wrapper-image...
error: The following command exited with error code 1:`

I don't know should I try to build this DLL and put it somewhere? What's the solution here?
Also it would be nice to have a little example how to incorporate TTF code and drawing text.

**Comment by MasterQ32** [comment]
Did you add the SDL2_image in your build script? SDL.zig doesn't take care of SDL_image and SDL_ttf

**Comment by ragnarlodbrok1992** [comment]
Can You explain what exactly needs to be done?
