### ISSUE TITLE
Missing GLtypes support - `SDL_GL`

### ISSUE THREAD

**Issue by kassane** [MasterQ32/SDL.zig#107]
I am trying to develop another player example for the [`libvlc-zig - issue#3`](https://github.com/kassane/libvlc-zig/issues/3) project using SDL2 but the referenced example uses OGL together.
However, the binding doesn't have access to the GL types (`GLint`, `GLfloat`, `GLchar`,...) and some functions are not available for use.
How would I get access to these `SDL_GL` features?

**Comment by MasterQ32** [comment]
For a fully featured OpenGL interface, you need a loader library like [zig-opengl](https://github.com/MasterQ32/zig-opengl), that will provide you with a well-defined OpenGL interface

**Comment by kassane** [comment]
Very interesting, will have a look at that.
I also checked the `gen_sdl.sh` script since the binding folder did not have the `SDL_opengl.zig` file.

**Comment by gluax** [comment]
I would still prefer the `SDL_GL_LoadLibrary`, is there any way we could support that?

**Comment by ikskuh** [comment]
Can you explain what you mean by that? The function itself is supported, as well as `SDL_GL_GetProcAddress`

**Comment by gluax** [comment]
I can do `sdl.c.SDL_GL_LoadLibrary`  but there didn't seem another way to call that with the wrapper unless I'm missing it?
