### ISSUE TITLE
sdl2_image not linked on macos

### ISSUE THREAD

**Issue by jmmk** [MasterQ32/SDL.zig#155]
When trying to run the example that includes the png image, I was getting several errors, e.g.

```
error: undefined reference to symbol _IMG_LoadBMP_RW
```

I was able to solve this by adding a line to my `build.zig`:

```
exe.linkSystemLibrary("sdl2_image");
```

If I am not mistaken, that line is missing here: https://github.com/MasterQ32/SDL.zig/blob/master/build.zig#L414

**Comment by MasterQ32** [comment]
Won't fix: See here (https://github.com/MasterQ32/SDL.zig/issues/47)
