### ISSUE TITLE
Sdk not linking sdl2_image 

### ISSUE THREAD

**Issue by Maskhjarna** [MasterQ32/SDL.zig#47]
When attempting to build on Arch Linux 5.16.8 I get this:
```
ld.lld: error: undefined symbol: IMG_Init
```

Adding this line to Sdk.zig seems to fix the problem:
```zig
// . . .

} else {
    // on linux, we should rely on the system libraries to "just work"
    exe.linkSystemLibrary("sdl2");
    exe.linkSystemLibrary("sdl2_image"); // <--
}

// . . .
```
Largely unfamiliar with the zig build system, so I might be doing something wrong.

**Comment by MasterQ32** [comment]
This is only right if you intend to link `sdl2_image`. Which is not that often the case. So this would require some kind of additional function in the Sdk.zig instead of adding it to a function that only links SDL2

**Comment by Maskhjarna** [comment]
Ah makes sense. I assumed the package would also provide some indirect means of linking ```sdl2_image```.

**Comment by MasterQ32** [comment]
> Ah makes sense. I assumed the package would also provide some indirect means of linking `sdl2_image`.

Feel free to make a PR in the style of the Sdk for SDL_image!
