### ISSUE TITLE
HOWTO use IMG

### ISSUE THREAD

**Issue by pierrec** [MasterQ32/SDL.zig#50]
Hello and thank you for this package, it makes SDL easier to use, and sorry if this is not the right place to ask!

I am trying to load some image and wanted to use the src/wrapper/image.zig components but I am running into compile errors, which I am unsure how to adress (sorry I am a Zig newbie).

```
error(link): undefined reference to symbol '_IMG_LoadTexture'
error(link):   first referenced in '.../zig-cache/o/20640cb1f414271a11369a39446aa7a6/sdl.o'
error: UndefinedSymbolReference
```

I did install sdl2_image view brew so I am not sure why it cannot find the lib.

Any tips on how to use loadTexture for instance?

Thanks!

**Comment by MasterQ32** [comment]
> `undefined reference to symbol '_IMG_LoadTexture'`

this means you have to link the `sdl2_image` library in your build script as well (it means it has found the type informatin, but not the function itself)

> Any tips on how to use loadTexture for instance?

You can use any C SDL_image tutorial to answer this question :blush:

**Comment by pierrec** [comment]
Ah thanks!

I have added:
```
exe.linkSystemLibrary("sdl2_image");
```

to my build.zig and it now works! :)
