### ISSUE TITLE
Zig std version supported.

### ISSUE THREAD

**Issue by P-Louw** [MasterQ32/SDL.zig#72]
Which version of the zig std is this library mainly aimed at?
I was using it with compiler version 0.9.1 up until yesterday.

The latest pr changes the pkg sources path to match the latest commit of the zig git
repo. Asking it here since I wasn't able to find this in the readme.

**Comment by MasterQ32** [comment]
If no specific version is mentioned, assume that `master` is tracked

**Comment by P-Louw** [comment]
Ok, thank you. Currently I am using mostly 0.9.1 on devices. Might switch to master then soon.
