### ISSUE TITLE
Could not build example with `Zig 0.9.1` + Linux

### ISSUE THREAD

**Issue by jjzajac** [MasterQ32/SDL.zig#75]
Atfer clone repo, i tried to build project i got that error:
```
λ zig build
./Sdk.zig:54:9: error: no member named 'source' in struct 'std.build.Pkg'
        .source = .{ .path = sdkRoot() ++ "/src/binding/sdl.zig" },
        ^
./Sdk.zig:82:9: error: no member named 'source' in struct 'std.build.Pkg'
        .source = .{ .path = sdkRoot() ++ "/src/wrapper/sdl.zig" },
   
```
I found that easiest fix is to change `source` to `path` because `std.build.Pkg` is changed.

---
I am new in `Zig` so i do not know if that solution is backward compatible.

**Comment by MasterQ32** [comment]
This library tracks Zig `master` on `master` branch. If you want to use it with `0.9.1`, you can either use an older commit or apply these changes locally
